#!/bin/bash
#SBATCH -N 1	
#SBATCH --job-name twin_ICA_mar12
#SBATCH --mem-per-cpu 72000
#SBATCH --constraint="largemem"
#SBATCH --output=output.ICA.mar12
#SBATCH --error=output_err.ICA.mar12
#SBATCH -o twin_ICA_mar12
#SBATCH -p batch
#SBATCH -t 72:00:00
#SBATCH -n 1
#----------------
# Job Submission
#----------------
umask 2

## THIS MUST BE A COMPLETE PATH TO THE JOB FILE
/projects/niblab/scripts/twin/ica_mar12.sh
