#!/bin/bash
#SBATCH -N 1    
#SBATCH --job-name ica_HDMZ
#SBATCH --mem-per-cpu 32000
#SBATCH --constraint="largemem"
#SBATCH --output=output.ICAHDMZ
#SBATCH --error=output_err.ICAHDMZ
#SBATCH -o ica_HDMZ
#SBATCH -p batch
#SBATCH -t 48:00:00
#SBATCH -n 1
#----------------
# Job Submission
#----------------
umask 2

## THIS MUST BE A COMPLETE PATH TO THE JOB FILE
/projects/niblab/scripts/twin/ica_HDMZ.sh
