#!/bin/bash
#SBATCH -N 1	
#SBATCH --job-name twin_ICA_test
#SBATCH --mem-per-cpu 32000
#SBATCH --constraint="largemem"
#SBATCH --output=output.MIGP_test
#SBATCH --error=output_err.MIGP_test
#SBATCH -o twin_ICA_test 
#SBATCH -p batch
#SBATCH -t 5:00:00
#SBATCH -n 1
#----------------
# Job Submission
#----------------
umask 2

## THIS MUST BE A COMPLETE PATH TO THE JOB FILE
/projects/niblab/scripts/twin/ICA_test.sh
